#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -layout no &
xinput set-prop `xinput | grep Touchpad | awk '{print $6}' | cut -d '=' -f 2` $(xinput list-props `xinput | grep Touchpad | awk '{print $6}' | cut -d '=' -f 2` | grep 'Tapping Enabled' | head -n 1 | awk '{print $(NF-1)}' | cut -d '(' -f 2 | cut -d ')' -f 1) 1 &
xinput set-prop `xinput | grep Touchpad | awk '{print $6}' | cut -d '=' -f 2` $(xinput list-props `xinput | grep Touchpad | awk '{print $6}' | cut -d '=' -f 2` | grep 'Natural Scrolling Enabled' | head -n 1 | awk '{print $(NF-1)}' | cut -d '(' -f 2 | cut -d ')' -f 1) 1 &
xsetroot -cursor_name left_ptr &
feh --bg-center ~/Pictures/wallpapers/active &
polybar &
/var/lib/flatpak/exports/bin/com.github.wwmm.pulseeffects  --gapplication-service &
xrdb $HOME/.Xresources &

	bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
